# Build settings
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Site settings
title: "Punk N' Poultry"
tagline: "God save the farm"
description: >
  Punk N Poultry Farm won’t sell you visions of the quiet country life.
  We’re more into the Buzzcocks than the bucolic, but we share the same vision as the Eat Local hipster crowd.
  Those smug bastards are onto something: sustainably-produced food that is grown well, farmed well and tastes good.
  What we don’t deliver in homespun charm, we make up for in hard work and delicious food.

theme: mere-blog-theme

paginate: 6
paginate_path: "/page:num"

collections:
  authors:
    output: true

google_analytics: UA-87190708-1

email: farm@punknpoultry.com
#blog logo
logo: "/assets/images/PnP_logo.png"
# blog cover
cover: "/assets/images/background_image7.jpg"

name: 'Punk N Poultry Farm'
author: 'Punk N Poultry Farm'
author_image: "/assets/images/PnP_logo.png"

url: "https://punknpoultry.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@punknpoultry'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
#twitter:	https://twitter.com/punknpoultry
facebook:  https://facebook.com/punknpoultry
github:	https://github.com/punknpoultry
youtube: https://www.youtube.com/@punknpoultryfarm
tiktok: https://www.tiktok.com/@tracy_punknpoultry

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

sass:
    style: compressed
